### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kuboschek** [OpenJUB/roomer#5]
- [ ] College Allocation (#2)
- [ ] Roommate System (#3)
- [ ] Room System (#4)
- [ ] Angular Material UI
- [ ] Results Viewer / Export
- [ ] Email Notifications
- [ ] Tall people applications system
- [ ] Tweaks to Django admin
